### ISSUE TITLE
TALENTO SANTIDAD DE BATALLA EN PALADIN REPRESION NO FUNCIONA

### ISSUE THREAD

**Issue by castel55** [Dev-Goliath/Bugtracker_Oficcial#65]
talento "santidad de batalla" bug: un talento crucial para poder incrementar el dps y por culpa del cual no renta nada reforjar el indice de celeridad, pues reduce el CD de golpe de cruzado y tormenta divina en base a tu celeridad. pierdes golpes de cruzado por unidad de tiempo, pierdes poder sagrado que no ganas, y pierdes veredictos de templario a consecuencia de ejecutar mas lentamente los golpes de cruzado como fuente de poder sagrado. no importa cuanto suba la celeridad con dicho talento activo, siempre tiene el CD en 4 seg. el golpe de cruzado.
![fgfgfg](https://user-images.githubusercontent.com/94983369/143785826-4e33c664-d3a1-4fbb-ab3c-b8698af79471.jpg)
![wefrbggh](https://user-images.githubusercontent.com/94983369/143785831-88f09673-b09c-4330-964d-c2e490b63cd0.jpg)
 nombre pj: Cj

**Comment by Dev-Goliath** [comment]
el talento funciona correctamente
