### ISSUE TITLE
Diarias joyería bug

### ISSUE THREAD

**Issue by CorderoJv** [Dev-Goliath/Bugtracker_Oficcial#68]
Al hacer las misiones de joyería no deja completar las misiones.  Te pide 3 jaspe dentado y al hacer la misión no te deja completar.
Mi pj es Vixxy para que me ayudes con esa misión por favor 

![A66AE3B1-8E40-4F8E-977B-06BA742BEB0A](https://user-images.githubusercontent.com/95264074/143977349-464bf33e-1817-4121-8988-2b30fdd8ffbd.jpeg)

**Comment by Dev-Goliath** [comment]
la mision funciona correctamente, verificar si estas en grupo normal o grupo de banda, las misiones diarias no cuentan por esas razones ya que son individuales
