### ISSUE TITLE
Material

### ISSUE THREAD

**Issue by Krausser88** [Dev-Goliath/Bugtracker_Oficcial#73]
Recorriendo el mundo buscando no sé encuentra ninguna Mena ni depósito de korio por ningún lugar de Azeroth impidiendo la creación de artefactos de quest

**Comment by Dev-Goliath** [comment]
![image](https://user-images.githubusercontent.com/42742610/148625715-01fbba8f-c43d-45a2-829f-690db3024563.png)
el material si está
