### ISSUE TITLE
martillo del honrado paladin tank

### ISSUE THREAD

**Issue by mienhasal** [Dev-Goliath/Bugtracker_Oficcial#76]
https://es.wowhead.com/spell=53595/martillo-del-honrado
https://es.wowhead.com/item=78479/bebedora-de-almas

mi paladin tiene equipado la bebedora de almas puedo usar todos los ataques menos martillo del honrado,
me sale una leyenda o mensaje que si quiero usar honrado debo equiparme armas de 1 mano.

si cambio de arma me deja usar el honrado.

por favor chequenlo ya que con anterioridad podia usar la bebedora 
![WoWScrnShot_122121_160632](https://user-images.githubusercontent.com/88505233/147006637-2f0e70dd-2f51-4ac7-a488-2c704fca8444.jpg)
![WoWScrnShot_122121_162343](https://user-images.githubusercontent.com/88505233/147006643-fd5d1580-5896-4cd8-8265-06706a2a937c.jpg)
![WoWScrnShot_122421_183754](https://user-images.githubusercontent.com/88505233/147374999-5471cee2-e19b-497b-ba2c-a55078229d75.jpg)

**Comment by Dev-Goliath** [comment]
las bebedoras fueron modificadas como arma de 2 manos debido a que podian equipar los picaros por esta razón te sale ese mensaje
